### ISSUE TITLE
Seed - Clas does not exist

### ISSUE THREAD

**Issue by kampit** [FbF/Laravel-Categories#1]
When I run

```
php artisan db:seed --class=Fbf\LaravelCategories\CategoriesTableBase
[ReflectionException]
Class FbfLaravelCategoriesCategoriesTableBase does not exist
```

I'm missing something here?

**Comment by neilcrookes** [comment]
Oops, sorry. Typo in the readme, it should have been

`php artisan db:seed --class=Fbf\LaravelCategories\CategoriesTableBaseSeeder`

I've corrected it now. Thanks for highlighting.
